### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by chstudebaker** [ian-deloach/BiteSize#2]
### Reviewer: Cole Studebaker
|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|
1. Accurately describes project purpose: Yep. I could totally use an app like this
2. Is professional and free of typos, slang, etc.: Good work on this.
3. Fully explains the problem and the solution: Yes. This sounds like a very useful project
4. Is understandable by the average person: Yes. I think this program would be useful and user friendly to almost anyone.
|**Design Documentation**|
1. Navigation/flow through the application is logical and easy to use.: Good work. Maybe add a new entity for managing monthly work? such as projects that cant be broken down in one week
2. The order in which values are displayed are logical and easy to understand\/use: Good work.
3. The order in which the form fields entered are logical and easy to understand/use: Dont see a form yet. Are you planning on doing fields for each week or each day?
4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens: As far as I can see. Definite room for improvement, but its a very promising start.
|**Data model/Database**|
1. Everything on the screens and problem statement/flow is represented in the model: Since the model isnt set up yet, I cant comment. But the user model looks like a good set up for a database
2. There is at least one 1-to-many relationship.: Yep.
3. The model represents good database design: yep. No ERD as of yet, so I cant verify, but from what i heard today, it sounds like a solid start.
|**Code**|
1. Proper Maven project structure is used: yes
2. a .gitignore file for IntelliJ Java projects has been implemented: yes
3. There is not any redundant or copy/paste code in the JSPs or classes: None that I saw
4. Classes are appropriately-sized (no monster classes)and property files are used appropriately(no hard-coded values): File structure looks good
5. Logging statements are used rather than System.out.println and printStackTrace.: Did you use this? I wasnt sure.
6. There are appropriate unit tests/code coverage.: N/A
7. No sensitive information is visible in the repository (secrets, passwords, etc): N/A

**Comment by pawaitemadisoncollege** [comment]
HI @chstudebaker - thank you for sharing your review of @ian-deloach's project.  

Your feedback would be improved by providing more detailed feedback.  For example, "Definite room for improvement, but it's a very promising start." What exactly should be improved?

Regarding your comment "Did you use this? I wasnt sure."  Did you review the code? There is a search feature in GitHub that can be really helpful if you are looking for something specific. Give it a try!
